version: 2.1

machine:
  pre:
    - mkdir ~/.cache/yarn

dependencies:
  cache_directories:
    - ~/.cache/yarn
  override:
    - yarn install

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    docker:
      - image: cimg/node:14.17-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v12-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v12-dependencies-

      - run: yarn install --prefer-offline --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v12-dependencies-{{ checksum "yarn.lock" }}

      # Lint
      - run: yarn affected:lint --base=origin/master --parallel

      # Test
      - run: yarn affected:test --base=origin/master --parallel

      # e2e
      #- run: yarn affected:e2e --base=origin/master

      # build
      - run: yarn build --configuration production
